### ISSUE TITLE
ERR_UNHANDLED_REJECTION

### ISSUE THREAD

**Issue by sdavids** [ionos-deploy-now/retrieve-project-info-action#9]
.github/workflows/ci.yaml
```yaml
      - uses: ionos-deploy-now/retrieve-project-info-action@v1.4.0
        id: project
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          project: ${{ secrets.IONOS_PROJECT_ID }}
          service-host: api-eu.ionos.space
```

⇓

```
Run ionos-deploy-now/retrieve-project-info-action@v1.4.0
  with:
    api-key: ***
    project: ***
    service-host: api-eu.ionos.space
  
node:internal/process/promises:389
      new UnhandledPromiseRejection(reason);
      ^
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "AxiosError: Request failed with status code 500".
    at throwUnhandledRejectionsMode (node:internal/process/promises:389:7)
    at processPromiseRejections (node:internal/process/promises:470:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
  code: 'ERR_UNHANDLED_REJECTION'
}
Node.js v20.18.0
```
